# Generated by Django 3.2.6 on 2021-10-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagem',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='avatar'),
        ),
    ]
