# Generated by Django 3.2.6 on 2021-10-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_auto_20211003_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldo',
            name='tipo',
            field=models.CharField(default='R', max_length=1),
        ),
    ]
