# Generated by Django 3.2.6 on 2021-10-23 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_alter_saldo_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saldo',
            options={'ordering': ('data',)},
        ),
    ]
